# Site settings
title: LaneDenson @ GitHub
email: lanedenson@lanedenson.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for my github.io page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lanedenson.github.io" # the base hostname & protocol for your site
twitter_username: lanedenson
github_username:  lanedenson

# Build settings
markdown: kramdown
