name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Set this to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false  # Disable bundler cache
      - name: Remove Gemfile.lock and clear bundle cache
        run: |
          rm -f Gemfile.lock
          bundle config --local path vendor/bundle
          bundle config --local deployment false
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Display _config.yml contents
        run: cat _config.yml
      - name: Build site
        run: bundle exec jekyll build --verbose
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4