name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false  # Set this to false to avoid using the cache
      - name: Remove Gemfile.lock
        run: rm -f Gemfile.lock
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --verbose
      - name: Build site
        run: |
          bundle exec jekyll build --trace
          ls -la _site  # List contents of _site directory
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site